#!/bin/bash

rm -f mx-servers

while read line; do
    dig +short mx $line | awk '{ print $2 }' >> mx-servers;
done<domains

sort mx-servers | uniq > final_mx-servers

while read -r line; do
    server=$line
    IP=`dig +short $server`
    maxtls=0

    OLDIFS=$IFS;
    IFS=':'
    echo "Currently running for: $server"
    certificates=$(/usr/bin/openssl s_client -connect $server:25  -starttls smtp -crlf -showcerts -tlsextdebug 2>&1 </dev/null | sed -n '/-----BEGIN/,/-----END/ {/-----BEGIN/ s/^/:/; p}');
    for certificate in ${certificates#:}; do
        echo $certificate | openssl x509 -noout -text | egrep 'Subject:'
        echo $certificate | openssl x509 -noout -text | egrep -A2 'Validity';
        echo $certificate | openssl x509 -noout -text | egrep -A1 'X509v3 Subject Alternative Name:';
    done;
    if [ "x${certificates[0]}" != "x" ];then
        MAXTLS=""
        MINTLS="False"
        echo "QUIT" | openssl s_client -connect $server:25 -starttls smtp -crlf -tls1_2 1>/dev/null 2>&1
        if [ "$?" -eq 0 ]; then
            MAXTLS="1.2"
        fi
        if [ "x$MAXTLS" = "x" ]; then
			echo "QUIT" | openssl s_client -connect $server:25 -starttls smtp -crlf -tls1_1 1>/dev/null 2>&1
			if [ "$?" -eq 0 ]; then
				MAXTLS="1.1"
			fi
		fi
        if [ "x$MAXTLS" = "x" ]; then
			echo "QUIT" | openssl s_client -connect $server:25 -starttls smtp -crlf -tls1 1>/dev/null 2>&1
			if [ "$?" -eq 0 ]; then
				MAXTLS="1.0"
			fi
		fi
        echo "MAX TLS version supported by $server ($IP) = $MAXTLS"
        echo "QUIT" | openssl s_client -connect $server:25 -starttls smtp -crlf -ssl3 1>/dev/null 2>&1
        if [ "$?" -eq 0 ]; then
            MINTLS="True"
        fi
        echo "Support for TLS versions <1.0 by $server ($IP) = $MINTLS"
    fi
IFS=$OLDIFS

done<final_mx-servers
